sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - sudo apt-get install snapd
  - sudo snap install hugo --classic
  - npm install

before_script:
  - npm install -g "gulpjs/gulp#4.0"

script:
  - npm run lint
  - hugo version
  - gulp

env:
  - HUGO_RELEASE=0.45.1

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
