sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v"$HUGO_RELEASE"/hugo_extended_"$HUGO_RELEASE"_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

before_script:
  - npm install -g "gulpjs/gulp#v4.0.0"

script:
  - npm run lint
  - hugo version
  - gulp

env:
  - HUGO_RELEASE=0.49

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
