sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - sudo apt-get install snapd
  - sudo snap install hugo --channel=extended/stable --classic
  - npm install

before_script:
  - npm install -g "gulpjs/gulp#v4.0.0"

script:
  - npm run lint
  - /snap/bin/hugo version
  - gulp

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
