sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - wget --retry-connrefused https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_extended_0.45.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

before_script:
  - npm install -g "gulpjs/gulp#4.0"

script:
  - npm run lint
  - hugo version
  - gulp

env:
  - HUGO_RELEASE=0.45.1

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
