baseurl: https://example.org
title: MoodleBox
theme: hugo-moodlebox-theme
themesDir: ../..
languageCode: en-us

# Site main language. Available strings translations in the theme's `/i18n` directory.
defaultContentLanguage: en

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Allow taxonomy term with special characters
preserveTaxonomyNames: true

languages:
  en:
    languageName: English
    title: MoodleBox
    description: A cool theme for Hugo
    about: MoodleBox is a cool theme for Hugo by [Nicolas Martignoni](https://twitter.com/nmartignoni)
    copyright: Copyright © 2018 onwards
    weight: 1
    contentDir: content/en
    # Format dates with Go's time formatting
    date_format: January 2, 2006
    menu:
      main:
      - identifier: home
        name: Home
        weight: 1

      - identifier: menu_one
        name: First menu
        weight: 2

      - parent: menu_one
        name: Knowledge base
        url: /help/
        weight: 1
      - parent: menu_one
        name: About MoodleBox Theme
        url: /help/about/
        weight: 2
      - parent: menu_one
        name: Contact
        url: /contact/
        weight: 3

      - identifier: menu_two
        name: Another menu
        weight: 3

      - parent: menu_two
        name: Install MoodleBox theme
        url: /help/install/
        weight: 1
      - parent: menu_two
        name: Create a theme
        url: /help/create-a-theme/
        weight: 2
      - parent: menu_two
        name: Go is for lovers
        url: /help/go-is-for-lovers
        weight: 3

    testimonials:
      enable: true
      subtitle: Here are some testimonials
      title: What people say

    clients:
      enable: true
      subtitle: These are some clients
      title: Our users

    topbar:
      enable: true
      text: "Contact us on info@example.com"

  fr:
    languageName: Français
    title: MoodleBox
    description: Un thème sympa pour Hugo
    about: MoodleBox est thème pour Hugo réalisé par [Nicolas Martignoni](https://twitter.com/nmartignoni)
    copyright: Copyright © 2018 et suivantes
    contentDir: content/fr
    weight: 2
    # Format dates with Go's time formatting
    date_format: 2 January 2006
    menu:
      main:
      - identifier: home
        name: Accueil
        weight: 1

      - identifier: menu_one
        name: Premier menu
        weight: 2

      - parent: menu_one
        name: Assistance
        url: /help/
        weight: 1
      - parent: menu_one
        name: À propos du thème MoodleBox
        url: /help/about/
        weight: 2
      - parent: menu_one
        name: Contact
        url: /contact/
        weight: 3

      - identifier: menu_two
        name: Un autre menu
        weight: 3

      - parent: menu_two
        name: Installer le thème MoodleBox
        url: /help/install/
        weight: 1
      - parent: menu_two
        name: Créer un thème
        url: /help/creer-un-theme/
        weight: 2
      - parent: menu_two
        name: Go is for lovers
        url: /help/go-is-for-lovers
        weight: 3

    testimonials:
      enable: true
      subtitle: Voici quelques témoignages
      title: Ce que les gens en disent

    clients:
      enable: true
      subtitle: Voici quelques-uns de nos clients
      title: Nos utilisateurs

    topbar:
      enable: true
      text: "Contactez-nous sur info@example.com"

  de:
    languageName: Deutsch
    title: MoodleBox
    description: Ein cooles Design für Hugo
    about: MoodleBox ist ein Design für Hugo realisiert von [Nicolas Martignoni](https://twitter.com/nmartignoni)
    copyright: Copyright © 2018 und später
    contentDir: content/de
    weight: 3
    # Format dates with Go's time formatting
    date_format: 2. January 2006
    menu:
      main:
      - identifier: home
        name: Home
        weight: 1

      - identifier: menu_one
        name: Erstes Menü
        weight: 2

      - parent: menu_one
        name: Dokumentation
        url: /help/
        weight: 1
      - parent: menu_one
        name: Über MoodleBox Design
        url: /help/about/
        weight: 2
      - parent: menu_one
        name: Kontakt
        url: /contact/
        weight: 3

      - identifier: menu_two
        name: Ein anderes Menü
        weight: 3

      - parent: menu_two
        name: MoodleBox Design installieren
        url: /help/install/
        weight: 1
      - parent: menu_two
        name: Design erstellen
        url: /help/design-erstellen/
        weight: 2
      - parent: menu_two
        name: Go is for lovers
        url: /help/go-is-for-lovers
        weight: 3

    testimonials:
      enable: true
      subtitle: Hier sind einige Meinungen von Personen
      title: Was Leute dazu sagen

    clients:
      enable: true
      subtitle: Hier sind einige Kunden
      title: Unsere Benutzer

    topbar:
      enable: true
      text: "Nehmen Sie Kontakt via info@example.com"

menu:
  topbar:
  - name: GitHub
    pre: <i class='fa fa-2x fa-github'></i>
    url: https://github.com/moodlebox/moodlebox-hugo-theme
    weight: 1
#  - name: Facebook
#    pre: <i class='fa fa-2x fa-facebook'></i>
#    url: https://facebook.com
#    weight: 2
  - name: Twitter
    pre: <i class='fa fa-2x fa-twitter'></i>
    url: https://twitter.com
    weight: 3
  - name: Email
    pre: <i class='fa fa-2x fa-envelope'></i>
    url: mailto:your@email.here
    weight: 4

params:
  author: Your Name
  address: ''
  defaultDescription: A cool theme for Hugo
  defaultKeywords:
  - Hugo
  - Hugo theme
  - Theme
  - Multilingual

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io email
  email: your@email.here

  logo: img/logo.png

  carousel:
    enable: true

  news:
    enable: true

  features:
    enable: true

  recent_posts:
    enable: true
    subtitle: ''
    title: ''

  see_more:
    enable: false
    icon: fa fa-file-code-o
    link_text: Check other homepages
    link_url: '#'
    subtitle: We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    title: Do you want to see more?

  viewMorePostLink: /help/

  widgets:
    categories: true
    search: true
    tags: true
    related: true
    recentnews: true

  # Enable/disable post-footer links
  privacy:
    enable: true
  cookies:
    enable: false
  license:
    enable: true
  donate:
    enable: true

  # Enable Matomo analytics by entering your tracking server and site id
  matomoAnalytics:
    siteid: ""
    matomoroot: "" # Do not add slashes

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
    - name: "keywords"
      weight: 200

    - name: "categories"
      weight: 100

    - name: "tags"
      weight: 50

    - name: "date"
      weight: 1
      pattern: "2006"

outputs:
  home: ["HTML", "JSON", "RSS"]
  page: ["HTML"]

permalinks:
  help: /help/:slug
